
provider: "genai" # [vertexai, genai, openai]
model_name: "gemini-2.5-pro"

# gemini project
credential_file: /path/to/credential.json
gemini_project_id: "your-project-name"
gemini_location: "your-location"

# gemini api key
gemini_api_key: null

# openai client
openai_api_key: "your-api-key"
base_url: "your-base-url"