
vlm_ckpt_path: 'TainU/RePlan-Qwen2.5-VL-7B'
diffusion_model_name: "black-forest-labs/FLUX.1-Kontext-dev"
pipeline_type: "flux"
# 设备配置
device: "cuda"
torch_dtype: "bfloat16"  # 或者 "float16", "float32"

# 基础配置
seed: 42
output_dir: "./output/replan_flux"
vlm_prompt_template_path: "replan.txt"

# 区域编辑配置
delete_main_prompt: False
replace_global_prompt: False
custom_global_prompt_text: "keep remaining parts of this image unchanged"
expand_value: 0.15
expand_mode: 'ratio'  # 'ratio' 或 'pixels'
